services:
  backend:
    build:
      context: ./backend
    container_name: crud-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: crud-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend